// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Na3XM_gUgSiWY3_iVQXYIvT5rz8XJFo',
    appId: '1:822388238551:web:ed4679fe96a607f6556892',
    messagingSenderId: '822388238551',
    projectId: 'uder-e31af',
    authDomain: 'uder-e31af.firebaseapp.com',
    storageBucket: 'uder-e31af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVAdfH6lskN7qx5jsRy2HVwmFGykqGuU',
    appId: '1:822388238551:android:b7e33d20eb32947f556892',
    messagingSenderId: '822388238551',
    projectId: 'uder-e31af',
    storageBucket: 'uder-e31af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbjgUkJ3MMt4JAvPEpFmbwJFLHpwjyx4',
    appId: '1:822388238551:ios:6d4a1961522d0a78556892',
    messagingSenderId: '822388238551',
    projectId: 'uder-e31af',
    storageBucket: 'uder-e31af.firebasestorage.app',
    iosBundleId: 'com.example.uniGator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbjgUkJ3MMt4JAvPEpFmbwJFLHpwjyx4',
    appId: '1:822388238551:ios:6d4a1961522d0a78556892',
    messagingSenderId: '822388238551',
    projectId: 'uder-e31af',
    storageBucket: 'uder-e31af.firebasestorage.app',
    iosBundleId: 'com.example.uniGator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Na3XM_gUgSiWY3_iVQXYIvT5rz8XJFo',
    appId: '1:822388238551:web:f68a0d42da273411556892',
    messagingSenderId: '822388238551',
    projectId: 'uder-e31af',
    authDomain: 'uder-e31af.firebaseapp.com',
    storageBucket: 'uder-e31af.firebasestorage.app',
  );

}